//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vydokh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "ФИОзаказа as \'Ф и озаказа\'",
            "Материал as \'Материал\'",
            "Материал.Имя as \'Материал\'"}, Hidden=new string[] {
            "Материал.Имя"})]
    [MasterViewDefineAttribute("ЗаказE", "Материал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОзаказа;
        
        private IIS.Vydokh.Материал fМатериал;
        
        private IIS.Vydokh.Отпуск fОтпуск;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// ФИОзаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ФИОзаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.ФИОзаказа CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОзаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ФИОзаказа Get start)

                // *** End programmer edit section *** (Заказ.ФИОзаказа Get start)
                string result = this.fФИОзаказа;
                // *** Start programmer edit section *** (Заказ.ФИОзаказа Get end)

                // *** End programmer edit section *** (Заказ.ФИОзаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ФИОзаказа Set start)

                // *** End programmer edit section *** (Заказ.ФИОзаказа Set start)
                this.fФИОзаказа = value;
                // *** Start programmer edit section *** (Заказ.ФИОзаказа Set end)

                // *** End programmer edit section *** (Заказ.ФИОзаказа Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Материал CustomAttributes)

        // *** End programmer edit section *** (Заказ.Материал CustomAttributes)
        [PropertyStorage(new string[] {
                "Материал"})]
        [NotNull()]
        public virtual IIS.Vydokh.Материал Материал
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Материал Get start)

                // *** End programmer edit section *** (Заказ.Материал Get start)
                IIS.Vydokh.Материал result = this.fМатериал;
                // *** Start programmer edit section *** (Заказ.Материал Get end)

                // *** End programmer edit section *** (Заказ.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Материал Set start)

                // *** End programmer edit section *** (Заказ.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (Заказ.Материал Set end)

                // *** End programmer edit section *** (Заказ.Материал Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Vydokh.Отпуск.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Отпуск CustomAttributes)

        // *** End programmer edit section *** (Заказ.Отпуск CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Отпуск"})]
        public virtual IIS.Vydokh.Отпуск Отпуск
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Отпуск Get start)

                // *** End programmer edit section *** (Заказ.Отпуск Get start)
                IIS.Vydokh.Отпуск result = this.fОтпуск;
                // *** Start programmer edit section *** (Заказ.Отпуск Get end)

                // *** End programmer edit section *** (Заказ.Отпуск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Отпуск Set start)

                // *** End programmer edit section *** (Заказ.Отпуск Set start)
                this.fОтпуск = value;
                // *** Start programmer edit section *** (Заказ.Отпуск Set end)

                // *** End programmer edit section *** (Заказ.Отпуск Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Vydokh.Заказ));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Заказ.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказ CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказ CustomAttributes)
    public class DetailArrayOfЗаказ : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Vydokh.DetailArrayOfЗаказ members)

        // *** End programmer edit section *** (IIS.Vydokh.DetailArrayOfЗаказ members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Заказ by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Заказ.
        /// </summary>
        public DetailArrayOfЗаказ(IIS.Vydokh.Отпуск fОтпуск) : 
                base(typeof(Заказ), ((ICSSoft.STORMNET.DataObject)(fОтпуск)))
        {
        }
        
        public IIS.Vydokh.Заказ this[int index]
        {
            get
            {
                return ((IIS.Vydokh.Заказ)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Vydokh.Заказ dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
