//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vydokh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материал.
    /// </summary>
    // *** Start programmer edit section *** (Материал CustomAttributes)

    // *** End programmer edit section *** (Материал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалE", new string[] {
            "Код as \'Код\'",
            "Имя as \'Имя\'",
            "Цвет as \'Цвет\'"})]
    [View("МатериалL", new string[] {
            "Код as \'Код\'",
            "Имя as \'Имя\'",
            "Цвет as \'Цвет\'"})]
    public class Материал : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fИмя;
        
        private string fЦвет;
        
        // *** Start programmer edit section *** (Материал CustomMembers)

        // *** End programmer edit section *** (Материал CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Имя CustomAttributes)

        // *** End programmer edit section *** (Материал.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Имя Get start)

                // *** End programmer edit section *** (Материал.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Материал.Имя Get end)

                // *** End programmer edit section *** (Материал.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Имя Set start)

                // *** End programmer edit section *** (Материал.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Материал.Имя Set end)

                // *** End programmer edit section *** (Материал.Имя Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Код CustomAttributes)

        // *** End programmer edit section *** (Материал.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Код Get start)

                // *** End programmer edit section *** (Материал.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Материал.Код Get end)

                // *** End programmer edit section *** (Материал.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Код Set start)

                // *** End programmer edit section *** (Материал.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Материал.Код Set end)

                // *** End programmer edit section *** (Материал.Код Set end)
            }
        }
        
        /// <summary>
        /// Цвет.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Цвет CustomAttributes)

        // *** End programmer edit section *** (Материал.Цвет CustomAttributes)
        [StrLen(255)]
        public virtual string Цвет
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Цвет Get start)

                // *** End programmer edit section *** (Материал.Цвет Get start)
                string result = this.fЦвет;
                // *** Start programmer edit section *** (Материал.Цвет Get end)

                // *** End programmer edit section *** (Материал.Цвет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Цвет Set start)

                // *** End programmer edit section *** (Материал.Цвет Set start)
                this.fЦвет = value;
                // *** Start programmer edit section *** (Материал.Цвет Set end)

                // *** End programmer edit section *** (Материал.Цвет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалE", typeof(IIS.Vydokh.Материал));
                }
            }
            
            /// <summary>
            /// "МатериалL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалL", typeof(IIS.Vydokh.Материал));
                }
            }
        }
    }
}
