//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vydokh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отпуск.
    /// </summary>
    // *** Start programmer edit section *** (Отпуск CustomAttributes)

    // *** End programmer edit section *** (Отпуск CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтпускE", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ОтпускE", "Заказ", "ЗаказE", true, "", "Заказ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтпускE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтпускL", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Отпуск : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПроводки;
        
        private IIS.Vydokh.Сотрудники fСотрудники;
        
        private IIS.Vydokh.DetailArrayOfЗаказ fЗаказ;
        
        // *** Start programmer edit section *** (Отпуск CustomMembers)

        // *** End programmer edit section *** (Отпуск CustomMembers)

        
        /// <summary>
        /// ДатаПроводки.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.ДатаПроводки CustomAttributes)

        // *** End programmer edit section *** (Отпуск.ДатаПроводки CustomAttributes)
        public virtual System.DateTime ДатаПроводки
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.ДатаПроводки Get start)

                // *** End programmer edit section *** (Отпуск.ДатаПроводки Get start)
                System.DateTime result = this.fДатаПроводки;
                // *** Start programmer edit section *** (Отпуск.ДатаПроводки Get end)

                // *** End programmer edit section *** (Отпуск.ДатаПроводки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.ДатаПроводки Set start)

                // *** End programmer edit section *** (Отпуск.ДатаПроводки Set start)
                this.fДатаПроводки = value;
                // *** Start programmer edit section *** (Отпуск.ДатаПроводки Set end)

                // *** End programmer edit section *** (Отпуск.ДатаПроводки Set end)
            }
        }
        
        /// <summary>
        /// Отпуск.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Отпуск.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Vydokh.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.Сотрудники Get start)

                // *** End programmer edit section *** (Отпуск.Сотрудники Get start)
                IIS.Vydokh.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Отпуск.Сотрудники Get end)

                // *** End programmer edit section *** (Отпуск.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.Сотрудники Set start)

                // *** End programmer edit section *** (Отпуск.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Отпуск.Сотрудники Set end)

                // *** End programmer edit section *** (Отпуск.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Отпуск.
        /// </summary>
        // *** Start programmer edit section *** (Отпуск.Заказ CustomAttributes)

        // *** End programmer edit section *** (Отпуск.Заказ CustomAttributes)
        public virtual IIS.Vydokh.DetailArrayOfЗаказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Отпуск.Заказ Get start)

                // *** End programmer edit section *** (Отпуск.Заказ Get start)
                if ((this.fЗаказ == null))
                {
                    this.fЗаказ = new IIS.Vydokh.DetailArrayOfЗаказ(this);
                }
                IIS.Vydokh.DetailArrayOfЗаказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Отпуск.Заказ Get end)

                // *** End programmer edit section *** (Отпуск.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отпуск.Заказ Set start)

                // *** End programmer edit section *** (Отпуск.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Отпуск.Заказ Set end)

                // *** End programmer edit section *** (Отпуск.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтпускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускE", typeof(IIS.Vydokh.Отпуск));
                }
            }
            
            /// <summary>
            /// "ОтпускL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускL", typeof(IIS.Vydokh.Отпуск));
                }
            }
        }
    }
}
